spring:
    application:
        name: demo
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
    sql:
        init:
            mode: always # 운영에서 사용 x
            data-locations:
                - classpath:sql/data.sql
            encoding: UTF-8
            